server.port: 8888
spring:
  application.name: config-server
  cloud:
    config:
      server:
        git:
          search-paths:
            - resource-service
            - clan-boss-service
            - api-gateway
          uri: https://github.com/sasha954/raid-helper-properties.git
          username: sasha954
          password: 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
#spring.cloud.config.server.native.searchLocations: file:${PWD}/config-server/config-repo
#spring.cloud.config.server.native.searchLocations: classpath:../../config-repo
